### ISSUE TITLE
Switch from IAttackStore implementation from temporary map store to SQL (or NoSQL) implementation

### ISSUE THREAD

**Issue by nitishm** [nitishm/vegeta-server#22]
The current implementation is using a simple map based storage, which serves for an ephemeral store.

Switch this over to SQL or NoSQL (MongoDB)

**Comment by ru-lai** [comment]
Hey @nitishm, I’m interested in doing this.
Are you leaning towards either one?

**Comment by nitishm** [comment]
Hey @ru-lai go ahead. I guess NoSQL would be better IMO but I am fine with either.
