### ISSUE TITLE
Add support for histogram format for GET /api/v1/report endpoint

### ISSUE THREAD

**Issue by nitishm** [nitishm/vegeta-server#23]
The report endpoint returns a JSON report by default. This task is to provide (query string based) support for the histogram `application/text` format for the `GET /api/v1/report?format=histogram`.

**Comment by Shivam010** [comment]
You are, actually talking about list all reports request: `GET /api/v1/report?format=histogram` or mean to provide the feature for get report by id request `GET /api/v1/report/<attackID>?format=histogram`.

I have suggestions and a PR, ready for the latter one. And if it is actually about list all request, then I would love to know more about it.

**Comment by nitishm** [comment]
@shivam010 it's for the latter `GET /api/v1/report/<attackID>?format=histogram`

Feel free to submit a PR
