### ISSUE TITLE
Add CreatedAt and UpdatedAt fields to models.AttackDetails

### ISSUE THREAD

**Issue by nitishm** [nitishm/vegeta-server#33]
Add the `CreatedAt` and `UpdatedAt` fields to `models.AttackDetails`, that get stored in the DB, to track the task submission time and the status update time.
The `CreatedAt` is set in `db.Add()` and the `UpdatedAt` is updated every time `db.Update()` is invoked with the `AttackDetails`.

**Comment by enc** [comment]
This change seems simple to me. Testing is more difficult. Since this project has no tests yet. Do you like a PR without tests? Otherwise, you have to wait a bit longer and you will get tests with the PR.

**Comment by nitishm** [comment]
@enc go ahead with the PR. You can hold off on the testing for now. Just verify that the status updates cause the time stamps to be updated (on fail, canceled, completed).

BTW I have a feature open for unit tests that I have started some work on, but would appreciate some help with if you are interested. LMK.

**Comment by nitishm** [comment]
@enc https://github.com/nitishm/vegeta-server/issues/40 is a pretty simple one, if you are interested.

**Comment by enc** [comment]
I will have a look later. Cheers! @nitishm
