### ISSUE TITLE
Move API documentation to new doc directory

### ISSUE THREAD

**Issue by nitishm** [nitishm/vegeta-server#47]
Move all the REST API usage examples from the `README.md` to a new `/docs` directory, under `usage.md`.

The `README.md` is too cluttered at the moment, and needs to be broken into smaller docs that can be linked from this file.

**Comment by jatinkumarg** [comment]
Since it was an easy fix, I have already submitted a [PR](https://github.com/nitishm/vegeta-server/pull/48)

Please review it and let me know if any further changes are required.
