### ISSUE TITLE
Wrap all upstream errors with errors.Wrap

### ISSUE THREAD

**Issue by nitishm** [nitishm/vegeta-server#56]
All upstream package errors should be wrapped with `errors.Wrap()` with an error message describing the error clause.

These errors should be propagated to caller, and eventually to the `main`, where they should be handled.

For example, take this block of code from `dispatcher.go`
```
if cancel {
		err := t.Cancel()
		if err != nil {
			d.log(fields).WithError(err).Error("failed to cancel task")
			return err
		}
}
```

and replace with,
```
if cancel {
		err := t.Cancel()
		if err != nil {
			d.log(fields).WithError(err).Error("failed to cancel task")
			return errors.Wrap(err, "failed to cancel task")
		}
}
```

This needs to be done across the package.

**Comment by rentziass** [comment]
Mind if I pick this up?

**Comment by nitishm** [comment]
@rentziass Feel free to work on this. Thanks !
