### ISSUE TITLE
Add more query params to `GET /api/v1/attack`

### ISSUE THREAD

**Issue by nitishm** [nitishm/vegeta-server#57]
Add more query params to `GET /api/v1/attack` endpoint, to filter attacks based on different attributes, like `status=completed` or `status=failed` to list successful vs failed attacks. 

Another query-able param would be to list attacks within a certain date/time range using the `createdAt` and `modifiedAt` fields. 

The `Target` as a collective should also be query-able based on the endpoint like `GET http://xyz.com`
 
There should be more params that would make sense, and I am open to suggestions, but we need to track all that work in this ticket.

**Comment by nitishm** [comment]
[x] Created query param for filtering by status.
[ ] Need query params for listing attacks in specified date range.

**Comment by prytoegrian** [comment]
I'm on it !

**Comment by nitishm** [comment]
[x] Created query param for filtering by status.
[x] Need query params for listing attacks in specified date range.
