### ISSUE TITLE
Create Dockerfile for the backend server

### ISSUE THREAD

**Issue by nitishm** [nitishm/vegeta-server#6]

**Comment by boydi0507** [comment]
Hey guys, 

I cloned your project and ran it locally. Super cool! I would love to get involved. I haven't contributed to any open source yet.

For clarification I assume you want a dockerfile that:
1. Uses the hosts networking
2. Installs go 1.11, golint, lint, etc
3. Clones the repo
4. Runs make and resolves dependencies
5. Serves on localhost

I'd like to take this ticket.

**Comment by nitishm** [comment]
@boydi0507 Thanks for trying it out and the excellent feedback !

> Uses the hosts networking

This step happens during `docker run`, so it doesn't need to be part of the Dockerfile creation.

> Installs go 1.11, golint, etc

So the thought was to use an official golang image from https://hub.docker.com/_/golang as the base image. 
This can be achieved by `FROM golang:1.11` which gives you a go1.11 base image( 1.11 is required for Go modules to work). 
This will give you a container with Go installed and GOPATH and other GO env's setup. 
You can skip golint and other validation binaries since we will not need to run it in the container.

> Clones the repo

Since we do not want to clone an upstream repo with every `docker build`. The dockerfile would use `COPY` syntax to copy over the project from the host path onto the container. Something on the lines of, 
```
FROM golang:1.11
ADD . /vegeta-server
WORKDIR /vegeta-server
```

> Runs make and resolves dependencies

Yes, we would `RUN make build` which should resolve dependencies and build the binary, into `./bin/vegeta-server`

```
RUN make build
```

> Serves on localhost

This can be done using `ENTRYPOINT` syntax as follows,
```
ENTRYPOINT ["bin/vegeta-server", "--ip=0.0.0.0", "--port=3000"]
```

Last step, and the most important in the dockerfile is to expose the port using 
```
EXPOSE 3000
```

Overall a minimal working dockerfile would look like,
```
FROM golang:1.11
ADD . /vegeta-server
WORKDIR /vegeta-server
RUN make build
ENTRYPOINT ["bin/vegeta-server", "--ip=0.0.0.0", "--port=3000"]
EXPOSE 3000
```

It would be helpful if you can leverage https://docs.docker.com/develop/develop-images/dockerfile_best-practices/ for the best practices by using `dockerfile-entrypoint.sh` scripts and a separate build context. Also adding a `.dockerignore` to skip copying the non-go (except makefile) file into the container, would reduce the image size. With the above example it copies every file over which is not ideal.

Thanks again for picking this up. Hopefully I have provided enough context.

Let me know if you need any help.
